baseURL: "https://lix.systems/"
theme: "lix"
languageCode: "en-us"

title: "Lix"

summaryLength: 20

params:
  title: "Lix"
  description: "Lix is an independent variant of the Nix package manager, developed by a team of open-source volunteers, and maintained by and for a passionate community of users."
  images:
    - "images/logo.png"

  logo: "lix_logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://twitter.com/LixProject"
    mastodon: "https://chaos.social/@lix_project"
    matrix: "https://matrix.to/#/#space:lix.systems"
    github: "https://github.com/lix-project"
    git: "https://git.lix.systems/lix-project"

  contact:
    - "General Inquiries: info@lix.systems"
    - "Security Reports: security@lix.systems"

  copyright: "Content licensed under CC-BY-SA-4.0 or LGPL-2.0-or-later."

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Lix"
      url: "/about"
      weight: 2

    - name: "FAQs"
      url: "/faq"
      weight: 2

    - name: "Team"
      url: "/team"
      weight: 3

    - name: "Community"
      url: "/community"
      weight: 4

    - name: News
      url: "/blog"
      weight: 5

    - name: "Docs"
      url: "https://docs.lix.systems/manual/lix/stable"
      weight: 6

    - name: "Code"
      url: "https://git.lix.systems/lix-project/lix"
      weight: 7

    - name: "Wiki"
      url: "https://wiki.lix.systems/books"
      weight: 8

  buttons:
    - name: "Install Lix"
      url: "/install"
      weight: 5
      pre: "btn btn-primary text-light"

  aboutus:
    - name: "Why Lix?"
      url: "/about#why-lix"
      weight: 1

    - name: "About Lix"
      url: "/about"
      weight: 2

    - name: "The Lix Team"
      url: "/team"
      weight: 4

    - name: "FAQs"
      url: "/faq"
      weight: 5

  resources:

    - name: "Wiki"
      url: "https://wiki.lix.systems"
      weight: 1

    - name: "Community"
      url: "/community"
      weight: 2

    - name: "Nix Resources"
      url: "/resources"
      weight: 2

    - name: "Source Repositories"
      url: "https://git.lix.systems/lix-project"
      weight: 4

    - name: "Quick Links"
      url: "/quicklinks"
      weight: 8


taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    style: manni
