baseURL: "https://lix.systems/"
theme: "lix"
languageCode: "en-us"

title: "Lix"

summaryLength: 20

params:
  title: "Lix"
  description: "Lix is an independent variant of the Nix package manager, developed by a team of open-source volunteers, and maintained by and for a passionate community of users."
  images:
    - "images/logo.png"

  logo: "lix_logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://twitter.com/LixProject"
    mastodon: "https://chaos.social/@lix_project"
    matrix: "https://matrix.to/#/#space:lix.systems"
    github: "https://github.com/lix-project"
    git: "https://git.lix.systems/lix-project"

  contact:
    - "General Inquiries: <a href=\"mailto:info@lix.systems\">info@lix.systems</a>"
    - "Security Reports: <a href=\"mailto:security@lix.systems\">security@lix.systems</a>"
    - "Matrix community: <a href=\"https://matrix.to/#/#space:lix.systems\">#space:lix.systems</a>"
    - "Zulip community: <a href=\"https://zulip.lix.systems\">zulip.lix.systems</a>"

  copyright: "Content licensed under CC-BY-SA-4.0 or LGPL-2.0-or-later."

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Lix"
      url: "/about"
      weight: 2

    - name: "About Us"
      url: "/team"
      weight: 2

    - name: "Community"
      url: "/community"
      weight: 3

    - name: "FAQs"
      url: "/faq"
      weight: 4

    - name: News
      url: "/blog"
      weight: 5

    - name: "Docs"
      url: "https://docs.lix.systems/manual/lix/stable"
      weight: 6

    - name: "Code"
      url: "https://git.lix.systems/lix-project/lix"
      weight: 7

    - name: "Wiki"
      url: "https://wiki.lix.systems/books"
      weight: 8

  buttons:
    - name: "Install Lix"
      url: "/install"
      weight: 5
      pre: "btn btn-primary text-light"

  aboutus:
    - name: "The Lix Team"
      url: "/team"
      weight: 3

    - name: "Our Governance"
      url: "/governance"
      weight: 4

    - name: "Community Standards"
      url: "/community-standards"
      weight: 5

    - name: "Project Values"
      url: "/values"
      weight: 6


  resources:
    - name: "Wiki"
      url: "https://wiki.lix.systems"
      weight: 1

    - name: "Docs"
      url: "https://docs.lix.systems/manual/lix/stable"
      weight: 2

    - name: "Git"
      url: "https://git.lix.systems/lix-project"
      weight: 4

    - name: "Quick Links"
      url: "/quicklinks"
      weight: 8


taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    style: manni
